/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    1: typeof import('./src/components/firstCard/card/1.vue')['default']
    FirstCard: typeof import('./src/components/firstCard/firstCard.vue')['default']
    Footer: typeof import('./src/components/footer/footer.vue')['default']
    Header: typeof import('./src/components/header/header.vue')['default']
    InnerTime: typeof import('./src/components/header/innerTime.vue')['default']
    Loading: typeof import('./src/components/login/loading.vue')['default']
    Login: typeof import('./src/components/login/login.vue')['default']
    Main: typeof import('./src/components/note/main.vue')['default']
    Nav: typeof import('./src/components/nav/index.vue')['default']
    Note: typeof import('./src/components/note/index.vue')['default']
    Note_search: typeof import('./src/components/note/note_search.vue')['default']
    Register: typeof import('./src/components/login/register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Second_a: typeof import('./src/components/secondCard/second_a.vue')['default']
    Second_search: typeof import('./src/components/secondCard/second_search.vue')['default']
    SecondCard: typeof import('./src/components/secondCard/index.vue')['default']
  }
}
